
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["588 589 1", "588 589 2", "588 589 3", "588 589 4", "588 589 5", "588 589 6", "588 589 7", "588 589 8", "588 589 9", "588 589 10", "588 589 11", "588 589 12", "588 589 13", "588 589 14", "588 589 15", "588 589 16", "588 589 17", "588 589 18", "588 589 19", "588 589 20", "588 589 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
