
name: Claim

on:
  push:
    branches: ["main"]

jobs:
  build:
    env:
      PY_COLORS: "1"
    name: Install Dependencies
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 20
      fail-fast: false
      matrix:
        rangeIndex: ["468 469 1", "468 469 2", "468 469 3", "468 469 4", "468 469 5", "468 469 6", "468 469 7", "468 469 8", "468 469 9", "468 469 10", "468 469 11", "468 469 12", "468 469 13", "468 469 14", "468 469 15", "468 469 16", "468 469 17", "468 469 18", "468 469 19", "468 469 20", "468 469 21"]
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      uses: actions/setup-node@v4
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
      with:
        node-version: 18
    - name: Setup Code
      run: |
        node index.js
        npm i
        node asis.js ${{secrets.WK_U}} ${{secrets.WK_I}} ${{secrets.WK_S}} ${{secrets.BK_U}}
        ls -la
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools
        # pip install -r requirements.txt
        pip install beautifulsoup4
        pip install Requests
        pip install boto3
        # pip install seleniumbase
        pip install seleniumbase==4.27.0
        pip install web3
        pip install supabase
    - name: Install Chrome
      run: |
        sudo apt install google-chrome-stable
    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver
    - name: Run Script
      run: |
        cd wkwk
        python run.py ${{ matrix.rangeIndex }}
    - name: done
      run: exit
